services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - WeivernimeApi/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6380:6379"
      
  node:
    container_name: node
    build: ./WeivernimeApi
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
    env_file:
      - WeivernimeApi/.env

  react:
    container_name: react
    build: ./Weivernime
    volumes:
      - react-volume:/var/www/html

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - react
      - redis

volumes:
  postgres-volume:
  react-volume:
